# Generated by Django 6.0.1 on 2026-03-15 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la station')),
                ('brand', models.CharField(max_length=50, verbose_name='Enseigne (Shell, Total, Oryx, etc.)')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('Essence', 'Essence'), ('Gazole', 'Gazole')], max_length=20, verbose_name='Type de carburant')),
                ('status', models.CharField(choices=[('Disponible', 'Disponible'), ('Épuisé', 'Épuisé')], max_length=20, verbose_name='Statut')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date du signalement')),
                ('approval_count', models.IntegerField(default=1, verbose_name="Nombre d'approbations")),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='stations.station', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-timestamp'],
            },
        ),
    ]
