# Generated by Django 6.0.1 on 2026-03-15 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_station_address_station_phone_station_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='manager_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nom du gérant'),
        ),
    ]
