# Generated by Django 5.2.12 on 2026-04-02 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_rename_stations_si_station_ts_idx_stations_si_station_d9dd7a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalement',
            name='fuel_type',
            field=models.CharField(choices=[('Essence', 'Essence'), ('Gazole', 'Gazole'), ('Électricité', 'Électricité')], max_length=20, verbose_name='Type de carburant'),
        ),
    ]
