# Generated by Django 5.2.12 on 2026-04-04 22:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_rename_stations_si_station_ts_idx_stations_si_station_d9dd7a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectriciteSignalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Disponible', 'Disponible'), ('Épuisé', 'Épuisé'), ('Instable', 'Instable')], max_length=20, verbose_name='Statut électricité')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du signalement')),
                ('approval_count', models.IntegerField(default=1, verbose_name="Nombre d'approbations")),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Commentaire')),
            ],
            options={
                'verbose_name': 'Signalement électricité',
                'verbose_name_plural': 'Signalements électricité',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ZoneElectrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nom de la zone')),
                ('zone_type', models.CharField(choices=[('Quartier', 'Quartier'), ('Secteur', 'Secteur'), ('Zone', 'Zone')], default='Quartier', max_length=20, verbose_name='Type de zone')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
                ('radius_km', models.FloatField(default=2.5, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Rayon (km)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zone électrique',
                'verbose_name_plural': 'Zones électriques',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='signalement',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Signalement carburant', 'verbose_name_plural': 'Signalements carburant'},
        ),
        migrations.RenameIndex(
            model_name='signalement',
            new_name='stations_si_station_d9dd7a_idx',
            old_name='stations_si_station_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='signalement',
            new_name='stations_si_fuel_ty_523f87_idx',
            old_name='stations_si_fuel_status_idx',
        ),
        migrations.RenameIndex(
            model_name='signalement',
            new_name='stations_si_timesta_898309_idx',
            old_name='stations_si_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='signalement',
            new_name='stations_si_ip_6e7b5a_idx',
            old_name='stations_si_ip_idx',
        ),
        migrations.RenameIndex(
            model_name='station',
            new_name='stations_st_brand_b28b50_idx',
            old_name='stations_st_brand_idx',
        ),
        migrations.RenameIndex(
            model_name='station',
            new_name='stations_st_is_acti_1d477b_idx',
            old_name='stations_st_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='station',
            new_name='stations_st_latitud_ba98b4_idx',
            old_name='stations_st_lat_lon_idx',
        ),
        migrations.AlterField(
            model_name='signalement',
            name='fuel_type',
            field=models.CharField(choices=[('Essence', 'Essence'), ('Gazole', 'Gazole')], max_length=20, verbose_name='Type de carburant'),
        ),
        migrations.AlterField(
            model_name='station',
            name='latitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='station',
            name='longitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude'),
        ),
        migrations.AddIndex(
            model_name='zoneelectrique',
            index=models.Index(fields=['zone_type'], name='stations_zo_zone_ty_e8787b_idx'),
        ),
        migrations.AddIndex(
            model_name='zoneelectrique',
            index=models.Index(fields=['is_active'], name='stations_zo_is_acti_b45a46_idx'),
        ),
        migrations.AddField(
            model_name='electricitesignalement',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_electricite', to='stations.zoneelectrique', verbose_name='Zone'),
        ),
        migrations.AddIndex(
            model_name='electricitesignalement',
            index=models.Index(fields=['zone', 'timestamp'], name='stations_el_zone_id_dec04c_idx'),
        ),
        migrations.AddIndex(
            model_name='electricitesignalement',
            index=models.Index(fields=['status'], name='stations_el_status_beb84a_idx'),
        ),
        migrations.AddIndex(
            model_name='electricitesignalement',
            index=models.Index(fields=['timestamp'], name='stations_el_timesta_a29184_idx'),
        ),
        migrations.AddIndex(
            model_name='electricitesignalement',
            index=models.Index(fields=['ip'], name='stations_el_ip_cd6c85_idx'),
        ),
    ]
