# Generated by Django 5.2.12 on 2026-04-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_electricitesignalement_zoneelectrique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitesignalement',
            name='duration_estimate_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Durée estimée (minutes)'),
        ),
        migrations.AddField(
            model_name='electricitesignalement',
            name='load_level',
            field=models.CharField(choices=[('Faible', 'Faible'), ('Normal', 'Normal'), ('Fort', 'Fort')], default='Normal', max_length=20, verbose_name='Niveau de charge'),
        ),
        migrations.AddField(
            model_name='electricitesignalement',
            name='source_type',
            field=models.CharField(choices=[('Ménage', 'Ménage'), ('Commerçant', 'Commerçant'), ('Observateur', 'Observateur')], default='Observateur', max_length=20, verbose_name='Type de source'),
        ),
        migrations.AlterField(
            model_name='electricitesignalement',
            name='status',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Coupure', 'Coupure'), ('Instable', 'Instable'), ('Retour récent', 'Retour récent'), ('Épuisé', 'Épuisé')], max_length=20, verbose_name='Statut électricité'),
        ),
    ]
