# Generated by Django 5.2.12 on 2026-04-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='is_pending',
            field=models.BooleanField(default=False, verbose_name='En attente de validation'),
        ),
        migrations.AddField(
            model_name='station',
            name='rejected_reason',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Motif de rejet'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['is_pending'], name='stations_st_is_pend_bb4dbb_idx'),
        ),
    ]
